[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Target your existing site
  NETLIFY_SITE_ID = "businessvibe"

# Add Content Security Policy headers
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://*.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.supabase.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://*.supabase.co https://*.amazonaws.com https://*.netlify.app https://images.pexels.com https://fonts.gstatic.com blob:; connect-src 'self' https://*.supabase.co wss://*.supabase.co; font-src 'self' https://fonts.gstatic.com; object-src 'none'; upgrade-insecure-requests;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/qr-redirect"
  to = "/qr-redirect.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true