[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Target your existing site
  NETLIFY_SITE_ID = "businessvibe"

[[redirects]]
  from = "/qr-redirect"
  to = "/qr-redirect.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true